name: communication
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  animated_widgets: ^1.0.6
  loading_indicator: ^1.1.0
  dio: ^3.0.9
  cross_connectivity: ^1.0.1
  scoped_model: ^1.0.1
  flutter_chip_tags: ^1.0.3
  intl: ^0.16.1
  process_run: ^0.10.12+3
  filepicker_windows: ^2.0.0
  fullscreen: ^1.0.3
  bitsdojo_window: ^0.0.9
  flutter_simple_calculator: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: Sunday Best
      fonts:
        - asset: assets/fonts/Sunday Best.ttf